---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-autoscaling
  failurePolicy: Fail
  name: mautoscaling-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autoscalings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-ceilometer
  failurePolicy: Fail
  name: mceilometer-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ceilometers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-cloudkitty
  failurePolicy: Fail
  name: mcloudkitty-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudkitties
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-metricstorage
  failurePolicy: Fail
  name: mmetricstorage-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricstorages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-telemetry
  failurePolicy: Fail
  name: mtelemetry-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - telemetries
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-autoscaling
  failurePolicy: Fail
  name: vautoscaling-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autoscalings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-ceilometer
  failurePolicy: Fail
  name: vceilometer-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ceilometers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-cloudkitty
  failurePolicy: Fail
  name: vcloudkitty-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudkitties
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-metricstorage
  failurePolicy: Fail
  name: vmetricstorage-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricstorages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-telemetry
  failurePolicy: Fail
  name: vtelemetry-v1beta1.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - telemetries
  sideEffects: None
