---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-autoscaling
  failurePolicy: Fail
  name: mautoscaling.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autoscalings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-availabiltiy
  failurePolicy: Fail
  name: mavailability.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - availability
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-ceilometer
  failurePolicy: Fail
  name: mceilometer.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ceilometers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-metricstorage
  failurePolicy: Fail
  name: mmetricstorage.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricstorages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-telemetry-openstack-org-v1beta1-telemetry
  failurePolicy: Fail
  name: mtelemetry.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - telemetries
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-autoscaling
  failurePolicy: Fail
  name: vautoscaling.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - autoscalings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-availability
  failurePolicy: Fail
  name: vavailability.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - availabilities
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-ceilometer
  failurePolicy: Fail
  name: vceilometer.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ceilometers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-metricstorage
  failurePolicy: Fail
  name: vmetricstorage.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricstorages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-telemetry-openstack-org-v1beta1-telemetry
  failurePolicy: Fail
  name: vtelemetry.kb.io
  rules:
  - apiGroups:
    - telemetry.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - telemetries
  sideEffects: None
