# permissions for end users to view cloudkitties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudkitty-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: telemetry-operator
    app.kubernetes.io/part-of: telemetry-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudkitty-viewer-role
rules:
- apiGroups:
  - telemetry.openstack.org
  resources:
  - cloudkitties
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - cloudkitties/status
  verbs:
  - get
