apiVersion: telemetry.openstack.org/v1beta1
kind: Ceilometer
metadata:
  name: ceilometer
  namespace: openstack
spec:
  secret: osp-secret
  notificationsBus:
    cluster: rabbitmq  # Required for receiving notifications from OpenStack services
  tls:
    caBundleSecretName: combined-ca-bundle
    secretName: cert-ceilometer-internal-svc
