---
# This is used by the default-telemetry job
- name: "Create the cluster-observability-operator subscription"
  hosts: "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig | default(ansible_env.HOME + '/.kube/config' ) }}"
    PATH: "{{ cifmw_path | default(ansible_env.PATH) }}"
  tasks:
    - name: Import tasks for creating COO subscription
      ansible.builtin.include_tasks: "create-coo-subscription.yaml"
