---
- hosts: all
  tasks:
    - name: remove ceilometer-agent container
      command: podman rm -f ceilometer_agent_compute

    - name: delete ceilometer config dirs
      become: true
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: absent
      with_items:
      - { 'path': /var/lib/openstack/config/containers/ceilometer_agent_compute.json}
      - { 'path': /var/lib/openstack/config/ceilometer}
      - { 'path': /var/log/containers/ceilometer}
      - { 'path': /etc/systemd/system/edpm_ceilometer_agent_compute.service}