name: Workflow for pre-commit run

on: [push, pull_request]

jobs:
  test:
    name: Run pre-commit jobs
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Checkout project code
        uses: actions/checkout@v3
      - name: Checkout openstack-k8s-operators-ci project
        uses: actions/checkout@v3
        with:
          repository: openstack-k8s-operators/openstack-k8s-operators-ci
          path: ./openstack-k8s-operators-ci
      - name: Install go deps
        run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          go get golang.stackrox.io/kube-linter/cmd/kube-linter
          GO111MODULE=on go install golang.stackrox.io/kube-linter/cmd/kube-linter
      - name: Install pre-commit
        run: |
          sudo apt install python3-pip
          pip install pre-commit
      - name: Run pre-commit on all files
        run: |
          source <(setup-envtest use -p env)
          pre-commit run --all-files
